# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "sourmash2fasta"
description: Extract genome FASTA files from Sourmash gather results using a lookup table
keywords:
  - sourmash
  - metagenomics
  - genome selection
  - fasta
tools:
  - "sourmash2fasta":
      description: "Custom script to parse Sourmash gather CSV, select top genomes per species, and concatenate selected genome FASTA files"
      licence: ["MIT"]
      identifier: ""

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - sourmash_results:
        type: file
        description: Sourmash gather CSV output
        pattern: "*.csv"
    - genome_species:
        type: file
        description: TSV mapping genome accession to species
        pattern: "*.tsv"
  - - lookup:
        type: file
        description: Sorted CSV mapping genome accession to FASTA filepath
        pattern: "*.csv"

output:
  genomes:
    - - meta:
          type: map
          description: Groovy Map containing sample information
      - "genomes_table.csv":
          type: file
          description: CSV table of selected genomes with file paths
          pattern: "genomes_table.csv"
  contigs:
    - - meta:
          type: map
          description: Groovy Map containing sample information
      - "contig_mapping.csv":
          type: file
          description: CSV mapping genome accession to contig ID
          pattern: "contig_mapping.csv"
  fasta:
    - - meta:
          type: map
          description: Groovy Map containing sample information
      - "genomes.fna":
          type: file
          description: Concatenated FASTA of all selected genomes
          pattern: "genomes.fna"
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"

authors:
  - "@tr11-sanger"
maintainers:
  - "@tr11-sanger"
