---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "chunkfastx"
description: Split a FASTA or FASTQ file into chunks by base count or read count
keywords:
  - split
  - chunk
  - fasta
  - fastq
tools:
  - "chunk_fastx":
      description: "Custom Python script to split FASTA/FASTQ files into chunks by target base or read count"
      licence: ["MIT"]
      identifier: ""

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - reads:
        type: file
        description: Input FASTA or FASTQ file, optionally gzipped
        pattern: "*.{fa,fasta,fq,fastq,fa.gz,fasta.gz,fq.gz,fastq.gz}"

output:
  chunked_reads:
    - - meta:
          type: map
          description: Groovy Map containing sample information
      - "chunked/*":
          type: file
          description: One or more chunked FASTA/FASTQ files
          pattern: "chunked/*"
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"

authors:
  - "@timrozday-mgnify"
maintainers:
  - "@timrozday-mgnify"
