# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "concatenate"
description: Concatenate a collection of files into a single output file
keywords:
  - concatenate
  - merge
  - files
tools:
  - "coreutils":
      description: "GNU core utilities (cat, find)"
      homepage: "https://www.gnu.org/software/coreutils/"
      licence: ["GPL-3.0-or-later"]
      identifier: ""

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - out_fn:
        type: string
        description: Output filename for the concatenated file
    - files:
        type: file
        description: Collection of files to concatenate

output:
  concatenated_file:
    - - meta:
          type: map
          description: Groovy Map containing sample information
      - "concatenated/*":
          type: file
          description: Single concatenated output file
          pattern: "concatenated/*"

authors:
  - "@timrozday-mgnify"
maintainers:
  - "@timrozday-mgnify"
