# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "seqstats"
description: Compute summary statistics (sequence and base counts) for FASTA/FASTQ files
keywords:
  - statistics
  - fasta
  - fastq
  - qc
tools:
  - "seq_stats":
      description: "Custom Python script for quick summary statistics on FASTA/FASTQ files"
      licence: ["MIT"]
      identifier: ""

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - seqs:
        type: file
        description: Input FASTA or FASTQ file, optionally gzipped
        pattern: "*.{fa,fasta,fq,fastq,fa.gz,fasta.gz,fq.gz,fastq.gz}"

output:
  stats:
    - - meta:
          type: map
          description: Groovy Map containing sample information
      - "stats.json":
          type: file
          description: JSON summary with read and base counts
          pattern: "stats.json"
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"

authors:
  - "@timrozday-mgnify"
maintainers:
  - "@timrozday-mgnify"
